name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main  # Rama principal
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure startup file
      run: |
        echo "startup.txt content:"
        cat startup.txt

    - name: Upload to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: sdignaweb  # <-- Nombre EXACTO de la App Service en Azure
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
